version: '3'

x-common-variables: &common-variables
  image: mariadb:10.5
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: mydb
  volumes:
    - ./mariadb/galera.cnf:/etc/mysql/conf.d/galera.cnf
  networks:
    - galera-network
  restart: always
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    interval: 30s
    timeout: 10s
    retries: 5

services:
  mariadb1:
    <<: *common-variables
    container_name: mariadb1
    volumes:
      - mariadb1_data:/var/lib/mysql
    command: --wsrep-new-cluster

  mariadb2:
    <<: *common-variables
    container_name: mariadb2
    volumes:
      - mariadb2_data:/var/lib/mysql
    command: --wsrep-new-cluster
    depends_on:
      - mariadb1

  mariadb3:
    <<: *common-variables
    container_name: mariadb3
    volumes:
      - mariadb3_data:/var/lib/mysql
    command: --wsrep-new-cluster
    depends_on:
      - mariadb1
      - mariadb2

  maxscale:
    image: mariadb/maxscale:latest
    container_name: maxscale
    volumes:
      - ./maxscale/maxscale.cnf:/etc/maxscale.cnf
    ports:
      - "4006:4006"  # MaxScale 서비스
      - "8989:8989"  # MaxScale 관리
    networks:
      - galera-network
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3
    restart: always
    healthcheck:
      test: ["CMD", "maxctrl", "list", "servers"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mariadb1_data:
  mariadb2_data:
  mariadb3_data:

networks:
  galera-network: