#파이썬 베이스
FROM python:3.11.9

#작업 디렉토리 설정
WORKDIR /app

#requirements 복사 및 패키지 설치

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]







