version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile-fastapi
    image: ba
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: always
    networks:
      - app
    container_name: backend
    depends_on:
      elasticsearch:
        condition: service_healthy

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile-streamlit
    image: fr
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./app:/app
    restart: always
    networks:
      - app
    container_name: frontend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
    ports:
      - '3001:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
volumes:
  grafana_storage: {}

networks:
  app:
    driver: bridge
