# github repository actions 페이지에 나타날 이름 
name: CI/CD using github actions & docker 

#event trigger 
#gyeom-server 브랜치에 push가 되었을 때 실행 
on: # 아래 상황에서 실행해 주세요.
  push: # push할 때
    branches:
      - gyeom-server
  # pull_request:
  #   branches:
  #     - main


jobs: 
  deploy:
    runs-on: ubuntu-latests
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: deploy to Ec2
      uses: appleboy/ssh-action@master # ssh 접속 
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_NAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script:
          cd /home/ubuntu/whatdo
          git pull